### ISSUE TITLE
'define' does not name a type

### ISSUE THREAD

**Issue by Sonsi79** [MNieddu91/Marlin-AI3M-BLTouch#15]
During compile in Arduino im getting these error:
**'define' does not name a type**

for the line:
**define X_DRIVER_TYPE  TMC2208_STANDALONE // comment out for stock drivers**

**Comment by Sonsi79** [comment]
Sorry my fault, I deleted the "#"

**Comment by NorbertRoller** [comment]
I fixed it by adding a #define in front of it.
The line reads: #define MarlinHAL hal;

Still strange is, that I get this error only on the BIGTREETECH-OCTOPUS-V1.0-master and not on the original Marlin-bugfix-2.0.x

Details: Win10 / German / PlatformIO
