### ISSUE TITLE
[FR] Mega-S Support

### ISSUE THREAD

**Issue by b-reich** [MNieddu91/Marlin-AI3M-BLTouch#16]
Please add support for the Mega-S upgrade kit.

The updated extrueder allows printing with tpu. The firmware from davidramiro supports the mega-s.

**Comment by davidramiro** [comment]
This firmware works fine with the Mega-S, just as mine does. The config of this repository even has the required e-steps set by default.

**Comment by Psychokiller1888** [comment]
Hey! Thanks for the work! Just to let you know, but on a default Mega S, all the axis are inverted

**Comment by agroezinger** [comment]
If you are using the stock drivers then yes, all axes are inverted. You have to change the stepper drivers in the configuration.h and recompile:

#define X_DRIVER_TYPE  TMC2208_STANDALONE // comment out for stock drivers
#define Y_DRIVER_TYPE  TMC2208_STANDALONE // comment out for stock drivers
#define Z_DRIVER_TYPE  TMC2208_STANDALONE // comment out for stock drivers
#define X2_DRIVER_TYPE TMC2208_STANDALONE
#define Y2_DRIVER_TYPE TMC2208_STANDALONE
#define Z2_DRIVER_TYPE TMC2208_STANDALONE // comment out for stock drivers
#define E0_DRIVER_TYPE TMC2208_STANDALONE // comment out for stock drivers
#define E1_DRIVER_TYPE TMC2208_STANDALONE // comment out for stock drivers
#define E2_DRIVER_TYPE TMC2208_STANDALONE
#define E3_DRIVER_TYPE TMC2208_STANDALONE
#define E4_DRIVER_TYPE TMC2208_STANDALONE
