### ISSUE TITLE
[BUG] BLTouch not deploying

### ISSUE THREAD

**Issue by Psychokiller1888** [MNieddu91/Marlin-AI3M-BLTouch#20]
**Describe the bug**
Flashed the latest sources after compiling via Arduino IDE. Had to reverse axis. Homing works fine. BLTouch 3.1 does self check and passes it, stays solid red after printer power on, with pin retracted. G29 starts the leveling cycle but the pin is never deployed, resulting in printer to stop by hitting Z endstops

**To Reproduce**
1. Start printer
2. G28
3. G29

**Expected behavior**

**Photos of the print / output of the terminal**
If applicable, add photos or console outputs to help explain your problem.

**Printer (please complete the following information):**
 - Firmware version: Cloned repo, compiled master
 - Through either Cura terminal or SD card bed leveling special menu item
 - i3 Mega, Mega-S

**Comment by Psychokiller1888** [comment]
Found only now some explanation on your wiki, sorry for the disturbance

**Comment by Psychokiller1888** [comment]
Nop, even after firmware adaptation, it won't deploy. Tried to reverse the black and white pins also

**Comment by Rich990** [comment]
Have you Adapter the version of your trigorilla board? That did it in my case.

**Comment by Psychokiller1888** [comment]
Nope, I did not. What do you mean by that?

**Comment by Rich990** [comment]
Somewhere in the firmware (i don’t know the exact line) it says something like „for trigorilla version xx put a ‚0‘ for version yy put ‚1‘....

**Comment by Rich990** [comment]
Line 1964-> if you have trigorilla 1.1 then Set a 1, otherwise 0.

**Comment by Psychokiller1888** [comment]
This did it, many thanks !!
